Bundes/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url, static
from django.conf import settings
from bundesinfo import views as bundesinfo_views

urlpatterns = [
    url(r'^$', bundesinfo_views.IndexPage.as_view(), name='index_page'),
    url(r'^bundes-info/', include('bundesinfo.urls', namespace='bundesinfo')),
    path('admin/', admin.site.urls),
]
if settings.DEBUG:
    urlpatterns += static.static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bundesinfo/urls.py
from django.conf.urls import url
from bundesinfo import views

app_name = 'bundesinfo'

urlpatterns = [
    url(r'standings/$', views.Standings.as_view(), name='standings'),
    url(r'next-round/$', views.NextRound.as_view(), name='next_round')
]

bundesinfo/models.py
from django.db import models
from django.core import validators


class TeamName(models.Model):
    """Holds information about teams"""

    teamID = models.IntegerField(validators=[
        validators.MinValueValidator(1),
    ])
    team_name = models.CharField(max_length=255)
    team_logo = models.URLField()
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    def __str__(self):
        return str(self.team_name)


class TeamStandings(models.Model):
    """Holds information about team standings"""

    class Meta:
        ordering = ('-points', '-wins')

    team = models.OneToOneField(TeamName, on_delete=models.CASCADE)
    points = models.IntegerField(validators=[
        validators.MinValueValidator(0),
    ], null=True)
    wins = models.IntegerField(validators=[
        validators.MinValueValidator(0),
        validators.MaxValueValidator(34),
    ], null=True)
    loses = models.IntegerField(validators=[
        validators.MinValueValidator(0),
        validators.MaxValueValidator(34),
    ], null=True)
    draws = models.IntegerField(validators=[
        validators.MinValueValidator(0),
        validators.MaxValueValidator(34),
    ], null=True)
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    def __str__(self):
        return str(self.team) + '-points: ' + str(self.points) + ' wins: ' + str(self.wins) + ' draws: ' + str(
            self.draws) + ' loses: ' + str(self.loses)

bundesinfo/views.py
from django.views.generic import TemplateView, ListView
from bundesinfo.models import TeamStandings
import requests
from django.utils import timezone


class IndexPage(TemplateView):
    template_name = 'bundesinfo/index.html'


class Standings(ListView):
    model = TeamStandings
    template_name = 'bundesinfo/standings.html'

    def get_queryset(self):
        qs = TeamStandings.objects.all()
        return qs


class NextRound(TemplateView):
    template_name = 'bundesinfo/next_round.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # get latest groupid/current matchday/
        current_group_order_id_url = 'https://www.openligadb.de/api/getcurrentgroup/bl1'
        group_order_request = requests.get(current_group_order_id_url).json()
        current_group_order_id = int(group_order_request['GroupOrderID'])
        # get next round matches
        url_address = 'https://www.openligadb.de/api/getmatchdata/bl1/2019/' + str(current_group_order_id + 1)
        result_json = requests.get(url_address).json()
        matches = []
        for item in result_json:
            format_str = r'%Y-%m-%dT%H:%M:%SZ'
            time = timezone.make_aware(timezone.datetime.strptime(item['MatchDateTimeUTC'], format_str))
            team1 = item['Team1']['ShortName']
            team2 = item['Team2']['ShortName']
            team1_logo = item['Team1']['TeamIconUrl']
            team2_logo = item['Team2']['TeamIconUrl']
            temp_dict = {
                'time': time,
                'team1': team1,
                'team2': team2,
                'team1_logo': team1_logo,
                'team2_logo': team2_logo,
            }
            matches.append(temp_dict)
        context['matches'] = matches
        return context

templates/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
{% load i18n %}

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>UBER RANKGING!</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/animate.css' %}">
    <link href="{% static 'css/prettyPhoto.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet"/>
</head>

<body>
<header>
    <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
        <div class="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                            data-target=".navbar-collapse.collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <div class="navbar-brand">
                        <a href="{% url 'index_page' %}"><h1><span>UBER</span>standings</h1></a>
                    </div>
                </div>

                <div class="navbar-collapse collapse">
                    <div class="menu">
                        <ul class="nav nav-tabs" role="tablist">
                            <li role="presentation">
                                <a href="{% url 'index_page' %}"
                                        {% block home_active %}{% endblock %}>
                                    Home
                                </a>
                            </li>
                            <li role="presentation">
                                <a href="{% url 'bundesinfo:standings' %}" {% block standings_active %}{% endblock %}>
                                    {% trans 'Standings' %}
                                </a>
                            </li>
                            <li role="presentation">
                                <a href="{% url 'bundesinfo:next_round' %}"
                                        {% block next_round_active %}{% endblock %}>
                                    {% trans 'Schedule' %}
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </nav>
</header>

{% block content %}
{% endblock %}

<footer>
    <div class="footer">
        <div class="container">
            <div class="social-icon">
                <div class="col-md-4">
                    <ul class="social-network">
                        <li><a href="#" class="fb tool-tip" title="Facebook"><i class="fa fa-facebook"></i></a></li>
                        <li><a href="#" class="twitter tool-tip" title="Twitter"><i class="fa fa-twitter"></i></a></li>
                        <li><a href="#" class="gplus tool-tip" title="Google Plus"><i class="fa fa-google-plus"></i></a>
                        </li>
                        <li><a href="#" class="linkedin tool-tip" title="Linkedin"><i class="fa fa-linkedin"></i></a>
                        </li>
                        <li><a href="#" class="ytube tool-tip" title="You Tube"><i class="fa fa-youtube-play"></i></a>
                        </li>
                    </ul>
                </div>
            </div>

            <div class="col-md-4 col-md-offset-4">
                <div class="copyright">
                    &copy; Company Theme. All Rights Reserved.
                    <div class="credits">
                        <!--
                          All the links in the footer should remain intact.
                          You can delete the links only if you purchased the pro version.
                          Licensing information: https://bootstrapmade.com/license/
                          Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/buy/?theme=Company
                        -->
                        Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a></div>
                </div>
            </div>
        </div>

        <div class="pull-right">
            <a href="#home" class="scrollup"><i class="fa fa-angle-up fa-3x"></i></a>
        </div>
    </div>
</footer>


<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'js/jquery-migrate.min.js' %}"></script>
<!-- Include all compiled plugins (below), or include individual files as needed -->
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/jquery.prettyPhoto.js' %}"></script>
<script src="{% static 'js/jquery.isotope.min.js' %}"></script>
<script src="{% static 'js/wow.min.js' %}"></script>
<script src="{% static 'js/functions.js' %}"></script>

</body>

</html>

templates/bundesinfo/index.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}
{% block home_active %}class="active"{% endblock %}
{% block content %}
    <section id="main-slider" class="no-margin">
        <div class="carousel slide">
            <div class="carousel-inner">
                <div class="item active" style="background-image: url({% static 'images/banner.jpg' %})">
                    <div class="container">
                        <div class="row slide-margin">
                            <div class="col-sm-6">
                                <div class="carousel-content">
                                    <h2 class="animation animated-item-1">UBER <span>{% trans 'STANDINGS' %}</span>
                                    </h2>
                                    <h3 class="animation animated-item-2"
                                        style="color: white; font-weight: bolder">
                                        Das Runde muss ins Eckige
                                    </h3>
                                    <a class="btn-slide animation animated-item-3"
                                       href="{% url 'bundesinfo:standings' %}">{% trans 'Check Standings' %}</a>
                                </div>
                            </div>

                            <div class="col-sm-6 hidden-xs animation animated-item-4">
                                <div class="slider-img">
                                    <img src="{% static 'images/soccer_ball.png' %}" class="img-responsive">
                                </div>
                            </div>

                        </div>
                    </div>
                </div>
                <!--/.item-->
            </div>
            <!--/.carousel-inner-->
        </div>
        <!--/.carousel-->
    </section>
    <!--/#main-slider-->

    <div class="feature">
        <div class="container">
            <div class="text-center">
                <div class="col-md-3">
                    <div class="hi-icon-wrap hi-icon-effect wow fadeInDown" data-wow-duration="1000ms"
                         data-wow-delay="300ms">
                        <i class="fa fa-book"></i>
                        <h2>Full Responsive</h2>
                        <p>Quisque eu ante at tortor imperdiet gravida nec sed turpis phasellus.</p>
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="hi-icon-wrap hi-icon-effect wow fadeInDown" data-wow-duration="1000ms"
                         data-wow-delay="600ms">
                        <i class="fa fa-laptop"></i>
                        <h2>Retina Ready</h2>
                        <p>Quisque eu ante at tortor imperdiet gravida nec sed turpis phasellus.</p>
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="hi-icon-wrap hi-icon-effect wow fadeInDown" data-wow-duration="1000ms"
                         data-wow-delay="900ms">
                        <i class="fa fa-heart-o"></i>
                        <h2>Full Responsive</h2>
                        <p>Quisque eu ante at tortor imperdiet gravida nec sed turpis phasellus.</p>
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="hi-icon-wrap hi-icon-effect wow fadeInDown" data-wow-duration="1000ms"
                         data-wow-delay="1200ms">
                        <i class="fa fa-cloud"></i>
                        <h2>Friendly Code</h2>
                        <p>Quisque eu ante at tortor imperdiet gravida nec sed turpis phasellus.</p>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="about">
        <div class="container">
            <div class="col-md-6 wow fadeInDown" data-wow-duration="1000ms" data-wow-delay="300ms">
                <h2>about us</h2>
                <img src="images/6.jpg" class="img-responsive"/>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus interdum erat libero, pulvinar
                    tincidunt leo consectetur eget. Curabitur lacinia pellentesque libero, pulvinar tincidunt leo
                    consectetur eget. Curabitur lacinia pellentesque libero,
                    pulvinar tincidunt leo consectetur eget. Curabitur lacinia pellentesque
                </p>
            </div>

            <div class="col-md-6 wow fadeInDown" data-wow-duration="1000ms" data-wow-delay="600ms">
                <h2>Template built with Twitter Bootstrap</h2>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus interdum erat libero, pulvinar
                    tincidunt leo consectetur eget. Curabitur lacinia pellentesque libero, pulvinar tincidunt leo
                    consectetur eget. Curabitur lacinia pellentesque libero,
                    pulvinar tincidunt leo consectetur eget. Curabitur lacinia pellentesque
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus interdum erat libero, pulvinar
                    tincidunt leo consectetur eget. Curabitur lacinia pellentesque libero, pulvinar tincidunt leo
                    consectetur eget. Curabitur lacinia pellentesque
                    libero, pulvinar tincidunt leo consectetur eget. Curabitur lacinia pellentesque
                </p>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus interdum erat libero, pulvinar
                    tincidunt leo consectetur eget. Curabitur lacinia pellentesque libero, pulvinar tincidunt leo
                    consectetur eget. Curabitur lacinia pellentesque
                    libero, pulvinar tincidunt leo consectetur eget. Curabitur lacinia pellentesque </p>
            </div>
        </div>
    </div>





{% endblock %}

templates/bundesinfo/next_round.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}
{% load tz %}
{% block next_round_active %}class="active"{% endblock %}

{% block content %}
    <div id="breadcrumb">
        <div class="container">
            <div class="breadcrumb">
                <li><a href="{% url 'index_page' %}">Home</a></li>
                <li>{% trans 'Schedule' %}</li>
            </div>
        </div>
    </div>
    <div class="aboutus">
        <div class="container" style="color: black">
            <h3>{% trans 'Schedule' %}</h3>
            <hr>
            {% for item in matches %}
                <div class="row">
                    <div class="col-xs-5 text-center">
                        <h4>
                            <img src="{{ item.team1_logo }}" class="img-responsive center-block"
                                 style="max-height: 50px;max-width: 50px">
                        </h4>

                        <h4>
                            {{ item.team1 }}
                        </h4>
                    </div>
                    <div class="col-xs-2 text-center">
                        vs
                    </div>
                    <div class="col-xs-5 text-center">
                        <h4>
                            <img src="{{ item.team2_logo }}" class="img-responsive center-block"
                                 style="max-height: 50px;max-width: 50px">
                        </h4>
                        <h4>
                            {{ item.team2 }}
                        </h4>
                    </div>
                </div>
                <div class="row">
                    <div class="col-xs-12 text-center">
                        <h4>
                            {{ item.time|localtime }}
                        </h4>
                    </div>
                </div>
                <hr>
            {% endfor %}


        </div>
    </div>

{% endblock %}

templates/bundesinfo/standings.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}
{% block standings_active %}class="active"{% endblock %}

{% block content %}
    <div id="breadcrumb">
        <div class="container">
            <div class="breadcrumb">
                <li><a href="{% url 'index_page' %}">Home</a></li>
                <li>{% trans 'Standings' %}</li>
            </div>
        </div>
    </div>
    <div class="aboutus">
        <div class="container">
            <h3>{% trans 'Standings' %}</h3>
            <hr>
            <div class="col-md-12 fadeInDown" data-wow-duration="1000ms" data-wow-delay="300ms">

                <div class="table-responsive" style="color: black">
                    <table class="table table-borderless" style="vertical-align: middle;">
                        <thead class="text-center">
                        <tr>
                            <th></th>
                            <th></th>
                            <th>{% trans 'Team' %}</th>
                            <th>{% trans 'Wins' %}</th>
                            <th>{% trans 'Draws' %}</th>
                            <th>{% trans 'Loses' %}</th>
                            <th>{% trans 'Points' %}</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for row in teamstandings_list %}
                            <tr>
                                <td>
                                    <h4>
                                        {{ forloop.counter }}
                                    </h4>
                                </td>
                                <td width="10%">
                                    <h4>
                                        <img src="{{ row.team.team_logo }}" class="img-responsive"
                                             style="max-height: 50px; max-width: 50px">
                                    </h4>
                                </td>
                                <td>
                                    <h4>
                                        {{ row.team.team_name }}
                                    </h4>
                                </td>
                                <td>
                                    <h4>
                                        {{ row.wins }}
                                    </h4>
                                </td>
                                <td>
                                    <h4>
                                        {{ row.draws }}
                                    </h4>
                                </td>
                                <td>
                                    <h4>
                                        {{ row.loses }}
                                    </h4>
                                </td>
                                <td>
                                    <h4>
                                        {{ row.points }}
                                    </h4>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
{% endblock %}